# Generated by Django 4.0.1 on 2022-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_date_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
